### ISSUE TITLE
Handle dimens in KMP

### ISSUE THREAD

**Issue by Fbada006** [Fbada006/ArtMaker#110]
hey @emmanuelmuturia , you can handle this one. Do research on how dimens are handled in KMP and implement it. 
Hint, they are not handled in the `dimens.xml`

**Comment by emmanuelmuturia** [comment]
> hey @emmanuelmuturia , you can handle this one. Do research on how dimens are handled in KMP and implement it. Hint, they are not handled in the `dimens.xml`

No worries. Is this directly related to #93 or will #93 be handled later?

**Comment by Fbada006** [comment]
They are related @emmanuelmuturia

**Comment by emmanuelmuturia** [comment]
> They are related @emmanuelmuturia

Got it...

**Comment by Fbada006** [comment]
Closed by #https://github.com/Fbada006/ArtMaker/pull/120
