### ISSUE TITLE
Detect Pressure from the drawing tool

### ISSUE THREAD

**Issue by CalebKL** [Fbada006/ArtMaker#20]
Based on the pressure that is coming from the drawing tool, we need to determine how much the line that is being drawn is being filled 
[Link](https://developer.android.com/codelabs/large-screens/advanced-stylus-support#3)

**Comment by Fbada006** [comment]
Hey @CalebKL , since #72 has been merged, you can get started on this. 

I propose adding a new setting in the stylus settings to enable/disable the pressure detection during drawing. If you have a better place, feel free to pursue it as well.
