### ISSUE TITLE
Create Github release pipeline

### ISSUE THREAD

**Issue by Fbada006** [Fbada006/ArtMaker#61]
The current setup to publish to maven requires that we create a github release, which triggers the `publish.yml` file. We need to automate the creation of the github release to make things easier

**Comment by Fbada006** [comment]
Hey @emmanuelmuturia , I would like you to get your hands dirty on this one. Do some reading and all that?

**Comment by emmanuelmuturia** [comment]
> Hey @emmanuelmuturia , I would like you to get your hands dirty on this one. Do some reading and all that? Are you up for it?

Yes, I am. Feel free to let me know if there is any other detail I need to be aware of besides the Issue Description...

**Comment by emmanuelmuturia** [comment]
@Fbada006 Will the automation only cover steps 4 up to 7 of [RELEASE.md (Creating a new release)](https://github.com/Fbada006/ArtMaker/blob/main/wiki/RELEASE.md) or is there any other step that needs to be included in the automation?

**Comment by Fbada006** [comment]
For now just step 4 to 7. We will refine it later

**Comment by emmanuelmuturia** [comment]
> For now just step 4 to 7. We will refine it later

No worries. Let me keep refining my solution as I have verified it works but it still needs some improvements. You can check out the Draft Release to confirm that the core details have been included...
![Screenshot from 2024-09-24 16-09-52](https://github.com/user-attachments/assets/af8d8874-a189-4d6c-98a3-704c874947ca)

**Comment by Fbada006** [comment]
A screenshot does not help me much @emmanuelmuturia . A link is a better idea

**Comment by Fbada006** [comment]
https://github.com/Fbada006/ArtMaker/releases/tag/untagged-3ad3dea401e5f4ba449e

**Comment by emmanuelmuturia** [comment]
> https://github.com/Fbada006/ArtMaker/releases/tag/untagged-3ad3dea401e5f4ba449e

This is noted...
