### ISSUE TITLE
Drawing and Stroke Settings Overlap

### ISSUE THREAD

**Issue by emmanuelmuturia** [Fbada006/ArtMaker#81]
- The drawing overlaps with the Stroke Width Slider. Ideally, the Stroke Width Slider should be layered on top of the drawing...

![image](https://github.com/user-attachments/assets/a26f890a-e8c1-4bd5-aed4-a56b285ab888)

**Comment by Fbada006** [comment]
@emmanuelmuturia , what is this issue about exactly?

**Comment by emmanuelmuturia** [comment]
> @emmanuelmuturia , what is this issue about exactly? You need to be add details to an issue explaining what it is about and what the fix should look like?

Done...
