### ISSUE TITLE
The rubbing button should not be enabled if there is no drawing

### ISSUE THREAD

**Issue by Fbada006** [Fbada006/ArtMaker#89]
As it is, the rubbing button is enabled regardless of whether there is a shape on screen or not. We need to add logic to conditionally enable or disable the rubbing button the same way we have enabled or disabled the undo, redo, and clear functionality.

**Comment by Fbada006** [comment]
Hey @emmanuelmuturia , this is also something you can take a look at. Do let me know if you have any issues.

**Comment by emmanuelmuturia** [comment]
> Hey @emmanuelmuturia , this is also something you can take a look at. Do let me know if you have any issues. Let this one take priority over the release pipeline issue please

No worries. Let me work on it tomorrow morning...
